title: Zacks Gallery
email: contact@zacksgallery.com
phone: +1-760-886-9991
description: >- 
  Zacks Gallery strives to create a bridge for humankind to connect and delight in the different expressions of each artist that wishes to convey his thoughts, visions, historical background, ideals and overall love and respect towards this World.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zacksgallery.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-MZ2M88R2BG
lang: us-en


social:
  name: Zacks Gallery
  links:
facebook_username: https://www.facebook.com/profile.php?id=61580905467307&sk=about
instagram_username:  https://www.instagram.com/ZacksGallery/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap

twitter:
  username: CentroRosarito
  card: summary
  
exclude:
  - HTML-MASTER/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
collections:
  artists:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      lang: "es-mx"
      lazy: true
      image: 
        path: /img/zacks-gallery-og.png.webp
        height: 512
        width: 190
      author: Rosarito Centro